import { useEffect, useState } from 'react';
import { api } from '../../api';
import Err from '../../components/Err';
import Field from '../../components/Field';
import Modal from '../../components/Modal';
import ProdBuscador from '../../components/ProdBuscador';
import { MEDIO_TXT, MEDIOS_SEL } from '../../constants/paymentMethods';
import { todayLocal, formatApiDate, apiDateToLocalInput } from '../../utils/dates';

function Proveedores() {
  const hoy = todayLocal();
  const [provs, setProvs] = useState([]), [deudas, setDeudas] = useState([]), [prods, setProds] = useState([]), [lista, setLista] = useState([]);
  const [err, setErr] = useState('');
  const [f, setF] = useState({ proveedor_id: '', fecha_pedido: hoy, nro: '', lineas: [{ producto_id: '', cantidad: 1, costo: '' }] });
  const [tried, setTried] = useState(false), [open, setOpen] = useState(false), [edit, setEdit] = useState(null), [ef, setEf] = useState({});
  const [pagoOpen, setPagoOpen] = useState(null), [pf, setPf] = useState({ medio_pago: 'efectivo', monto: '', descuento: '' });
  const [provConfig, setProvConfig] = useState(null), [cf, setCf] = useState({ pronto_pago_dias: '', pronto_pago_porcentaje: '' });
  const [nf, setNf] = useState({ nombre: '', contacto: '', telefono: '', alias: '', dias_entrega: '', pronto_pago_dias: '', pronto_pago_porcentaje: '' });

  const fmt = n => '$' + (+(n || 0)).toLocaleString('es-AR', { minimumFractionDigits: 2 });
  const costoBase = pid => (prods.find(p => String(p.id) === String(pid)) || {}).precio_costo || 0;
  const deudaDe = id => (deudas.find(d => d.id === id) || {}).deuda || 0;
  const provDe = id => provs.find(p => String(p.id) === String(id)) || {};
  const lineaTotal = l => (+l.cantidad || 0) * (l.costo === '' ? costoBase(l.producto_id) : +l.costo);
  const totalForm = ls => ls.reduce((a, l) => a + lineaTotal(l), 0);

  const loadBase = async () => { try { const [p, d, pr] = await Promise.all([api.proveedores(), api.deudasProv(), api.prods().catch(() => [])]); setProvs(p); setDeudas(d); setProds(pr); } catch (e) { setErr(e.message); } };
  const load = async () => { try { setLista(await api.compras({})); } catch (e) { setErr(e.message); } };
  const recargar = () => { loadBase(); load(); };
  useEffect(() => { loadBase(); load(); }, []);
  const setLinea = (i, patch) => setF({ ...f, lineas: f.lineas.map((l, j) => j === i ? { ...l, ...patch } : l) });

  const guardar = async () => { setTried(true); if (!f.proveedor_id || !f.nro.trim() || f.lineas.some(l => !l.producto_id || !(+l.cantidad >= 1))) return; try { await api.createCompra({ proveedor_id: +f.proveedor_id, nro_boleta: f.nro.trim(), fecha_pedido: f.fecha_pedido, detalles: f.lineas.map(l => ({ producto_id: +l.producto_id, cantidad: +l.cantidad, ...(l.costo === '' ? {} : { costo_unitario: +l.costo }) })), pagado: false, medio_pago: null }); setF({ proveedor_id: '', fecha_pedido: hoy, nro: '', lineas: [{ producto_id: '', cantidad: 1, costo: '' }] }); setTried(false); recargar(); } catch (e) { alert(e.message); } };
  const abrirPago = c => { setPagoOpen(c); const sugerido = +c.sugerencia_pronto_pago || 0; setPf({ medio_pago: c.medio_pago || 'efectivo', monto: Math.max(0, (+c.saldo_pendiente || 0) - sugerido).toFixed(2), descuento: sugerido ? sugerido.toFixed(2) : '' }); };
  const registrarPago = async () => { if (!pagoOpen) return; const monto = +pf.monto || 0, descuento = +pf.descuento || 0; if (monto + descuento <= 0) { alert('Ingresá un monto o descuento.'); return; } try { await api.pagarCompra(pagoOpen.id, { medio_pago: pf.medio_pago, monto, descuento }); setPagoOpen(null); recargar(); } catch (e) { alert(e.message); } };
  const entregar = async c => { if (!confirm(`Marcar pedido #${c.id} (${c.nro_boleta}) como entregado? Entra el stock.`)) return; try { await api.entregarCompra(c.id); recargar(); } catch (e) { alert(e.message); } };
  const borrar = async c => { if (!confirm(`Borrar pedido #${c.id}? Solo si no está entregado y no tiene pagos.`)) return; try { await api.deleteCompra(c.id); recargar(); } catch (e) { alert(e.message); } };
  const abrirEdit = c => { setEdit(c); setEf({ nro: c.nro_boleta, fecha: apiDateToLocalInput(c.fecha_pedido), medio: c.medio_pago || 'efectivo', lineas: (c.detalles || []).map(d => ({ producto_id: d.producto_id, cantidad: d.cantidad, costo: d.costo_unitario })) }); };
  const guardarEdit = async () => { if (!ef.nro.trim()) { alert('N° de boleta requerido'); return; } if (edit?.pagos?.length && !edit.fecha_entrega) { alert('Una compra con pagos registrados ya no permite editar sus líneas.'); return; } try { await api.patchCompra(edit.id, { nro_boleta: ef.nro.trim(), fecha_pedido: ef.fecha, medio_pago: ef.medio || null, ...(!edit.fecha_entrega && !(edit.pagos || []).length ? { detalles: ef.lineas.map(l => ({ producto_id: +l.producto_id, cantidad: +l.cantidad, costo_unitario: +l.costo })) } : {}) }); setEdit(null); recargar(); } catch (e) { alert(e.message); } };
  const abrirConfig = p => { setProvConfig(p); setCf({ pronto_pago_dias: p.pronto_pago_dias ?? '', pronto_pago_porcentaje: p.pronto_pago_porcentaje ?? '' }); };
  const guardarConfig = async () => { try { await api.patchProv(provConfig.id, { pronto_pago_dias: cf.pronto_pago_dias === '' ? null : +cf.pronto_pago_dias, pronto_pago_porcentaje: cf.pronto_pago_porcentaje === '' ? null : +cf.pronto_pago_porcentaje }); setProvConfig(null); recargar(); } catch (e) { alert(e.message); } };

  const selProv = provDe(f.proveedor_id);
  return <section>
    <div className="sec-head"><h2>Distribuidoras · Pedidos</h2><button className="fab" onClick={() => setOpen(true)}>+ Nueva</button></div><Err e={err} />
    <div className="sale-box"><h3>Registrar pedido</h3><div className="row"><Field label="Distribuidora" error={tried && !f.proveedor_id ? 'Elegí una' : ''}><select value={f.proveedor_id} onChange={e => setF({ ...f, proveedor_id: e.target.value })}><option value="">Elegir…</option>{provs.map(p => <option key={p.id} value={p.id}>{p.nombre}</option>)}</select></Field><Field label="Fecha del pedido"><input type="date" value={f.fecha_pedido} max={hoy} onChange={e => setF({ ...f, fecha_pedido: e.target.value })} /></Field><Field label="N° Boleta" error={tried && !f.nro.trim() ? 'Completá' : ''}><input value={f.nro} onChange={e => setF({ ...f, nro: e.target.value })} /></Field></div>{selProv.id && <p className="muted small">📦 Entregas: <b>{selProv.dias_entrega || '—'}</b>{selProv.alias ? <> · Alias: <b>{selProv.alias}</b></> : null} · Debe: <b>{fmt(deudaDe(selProv.id))}</b>{selProv.pronto_pago_dias != null && selProv.pronto_pago_porcentaje > 0 ? <> · Pronto pago: <b>{selProv.pronto_pago_porcentaje}% en {selProv.pronto_pago_dias} días</b></> : null}<button className="ghost" onClick={() => abrirConfig(selProv)}>configurar</button></p>}
      {f.lineas.map((l, i) => <div className="line" key={i}><Field className="lp" label="Producto" error={tried && !l.producto_id ? 'Elegí uno' : ''}><ProdBuscador prods={prods} value={l.producto_id} allowSinStock onChange={id => setLinea(i, { producto_id: id })} /></Field><Field className="lc" label="Cantidad"><input type="number" min="1" value={l.cantidad} onChange={e => setLinea(i, { cantidad: e.target.value })} /></Field><Field className="lv" label="Costo unit." hint={`Lista $${costoBase(l.producto_id)}`}><input type="number" min="0" value={l.costo} onChange={e => setLinea(i, { costo: e.target.value })} /></Field>{f.lineas.length > 1 && <button className="ghost" onClick={() => setF({ ...f, lineas: f.lineas.filter((_, j) => j !== i) })}>-</button>}</div>)}
      <div className="modal-actions"><button className="ghost" onClick={() => setF({ ...f, lineas: [...f.lineas, { producto_id: '', cantidad: 1, costo: '' }] })}>Agregar producto</button><span style={{ flex: 1 }} /><b>Total: {fmt(totalForm(f.lineas))}</b><button onClick={guardar}>Guardar pedido</button></div></div>

    <h3>Pedidos {lista.length > 0 && <span className="muted">· {lista.length}</span>}</h3>{lista.length === 0 ? <p className="muted">Sin pedidos todavía.</p> : <ul className="peds-list">{lista.map(c => <li key={c.id} className="ped-card"><div className="ped-head"><b>#{c.id} · {c.proveedor_nombre}</b><b className="in">{fmt(c.monto)}</b></div><div className="muted small ped-meta">Boleta {c.nro_boleta} · Pedido {formatApiDate(c.fecha_pedido)} · {c.detalles?.length || 0} producto{(c.detalles?.length || 0) === 1 ? '' : 's'}</div>{(c.pagos || []).length > 0 && <div className="det"><b>Pagos</b>{c.pagos.map(pg => <div className="det-line" key={pg.id}><span>{pg.fecha ? formatApiDate(pg.fecha) : 'Histórico'} · {MEDIO_TXT[pg.medio] || pg.medio}</span><span>{fmt(pg.monto)}{+pg.descuento > 0 ? ` · dto ${fmt(pg.descuento)}` : ''}</span></div>)}</div>}{c.detalles?.length > 0 && <div className="det">{c.detalles.map(d => <div className="det-line" key={d.id}><span>{d.producto_nombre || `prod ${d.producto_id}`} ×{d.cantidad}</span><span>{fmt(d.subtotal)}</span></div>)}</div>}<div className="ped-foot"><span className="ped-badges">{c.fecha_entrega ? <span className="badge ok">Entregada</span> : <span className="badge out">Sin entregar</span>} {c.saldo_pendiente <= 0.01 ? <span className="badge ok">Saldada</span> : <span className="badge out">Debe {fmt(c.saldo_pendiente)}</span>} {c.total_descuentos > 0 && <span className="badge ok">Dto {fmt(c.total_descuentos)}</span>}</span><span className="ped-actions">{!c.fecha_entrega && <button onClick={() => entregar(c)}>marcar entregado</button>}{c.saldo_pendiente > 0.01 && <button onClick={() => abrirPago(c)}>registrar pago</button>}<button onClick={() => abrirEdit(c)}>editar</button>{!c.fecha_entrega && !c.pagado && !(c.pagos || []).length && <button onClick={() => borrar(c)}>borrar</button>}</span></div></li>)}</ul>}

    <Modal open={!!pagoOpen} onClose={() => setPagoOpen(null)} title="Registrar pago"><p className="muted small">Compra #{pagoOpen?.id} · Saldo {fmt(pagoOpen?.saldo_pendiente)}{+pagoOpen?.sugerencia_pronto_pago > 0 ? <> · Sugerencia pronto pago {fmt(pagoOpen.sugerencia_pronto_pago)}</> : null}</p><Field label="Medio"><select value={pf.medio_pago} onChange={e => setPf({ ...pf, medio_pago: e.target.value })}>{MEDIOS_SEL.map(([v,t]) => <option key={v} value={v}>{t}</option>)}</select></Field><Field label="Monto que sale de caja" hint="Admite pagos parciales"><input type="number" min="0" step="0.01" value={pf.monto} onChange={e => setPf({ ...pf, monto: e.target.value })} /></Field><Field label="Descuento aplicado" hint="Reduce la deuda sin salir de caja"><input type="number" min="0" step="0.01" value={pf.descuento} onChange={e => setPf({ ...pf, descuento: e.target.value })} /></Field><div className="modal-actions"><button className="ghost" onClick={() => setPagoOpen(null)}>Cancelar</button><button onClick={registrarPago}>Registrar</button></div></Modal>
    <Modal open={!!edit} onClose={() => setEdit(null)} title={edit ? `Pedido #${edit.id} · ${edit.proveedor_nombre}` : 'Editar'} wide><div className="grid"><Field label="N° Boleta"><input value={ef.nro || ''} onChange={e => setEf({ ...ef, nro: e.target.value })} /></Field><Field label="Fecha del pedido"><input type="date" value={ef.fecha || ''} onChange={e => setEf({ ...ef, fecha: e.target.value })} /></Field><Field label="Medio de pago"><select value={ef.medio || 'efectivo'} onChange={e => setEf({ ...ef, medio: e.target.value })}>{MEDIOS_SEL.map(([v,t]) => <option key={v} value={v}>{t}</option>)}</select></Field><Field label="Entrega"><input value={edit?.fecha_entrega ? apiDateToLocalInput(edit.fecha_entrega) : 'Sin entregar'} disabled /></Field></div>{!edit?.fecha_entrega && !(edit?.pagos || []).length && <><h3>Líneas</h3>{(ef.lineas || []).map((l,i)=><div className="line" key={i}><Field className="lp" label="Producto"><ProdBuscador prods={prods} value={l.producto_id} allowSinStock onChange={id => setEf({ ...ef, lineas: ef.lineas.map((x,j)=>j===i?{...x,producto_id:id}:x) })}/></Field><Field className="lc" label="Cantidad"><input type="number" min="1" value={l.cantidad} onChange={e => setEf({ ...ef, lineas: ef.lineas.map((x,j)=>j===i?{...x,cantidad:e.target.value}:x) })}/></Field><Field className="lv" label="Costo"><input type="number" min="0" value={l.costo} onChange={e => setEf({ ...ef, lineas: ef.lineas.map((x,j)=>j===i?{...x,costo:e.target.value}:x) })}/></Field></div>)}</>}<div className="modal-actions"><button className="ghost" onClick={() => setEdit(null)}>Cerrar</button>{!edit?.pagos?.length && !edit?.fecha_entrega && <button onClick={guardarEdit}>Guardar cambios</button>}</div></Modal>
    <Modal open={!!provConfig} onClose={() => setProvConfig(null)} title={provConfig ? `Pronto pago · ${provConfig.nombre}` : 'Pronto pago'}><Field label="Plazo en días" hint="Ej: 7"><input type="number" min="0" value={cf.pronto_pago_dias} onChange={e => setCf({ ...cf, pronto_pago_dias: e.target.value })}/></Field><Field label="Descuento %" hint="Ej: 5"><input type="number" min="0" max="100" step="0.01" value={cf.pronto_pago_porcentaje} onChange={e => setCf({ ...cf, pronto_pago_porcentaje: e.target.value })}/></Field><div className="modal-actions"><button className="ghost" onClick={() => setProvConfig(null)}>Cancelar</button><button onClick={guardarConfig}>Guardar</button></div></Modal>
    <Modal open={open} onClose={() => setOpen(false)} title="Nueva distribuidora"><Field label="Nombre*"><input value={nf.nombre} onChange={e => setNf({ ...nf,nombre:e.target.value })}/></Field><Field label="Alias"><input value={nf.alias} onChange={e => setNf({ ...nf,alias:e.target.value })}/></Field><Field label="Entregas"><input value={nf.dias_entrega} onChange={e => setNf({ ...nf,dias_entrega:e.target.value })}/></Field><Field label="Pronto pago · días"><input type="number" min="0" value={nf.pronto_pago_dias} onChange={e => setNf({ ...nf,pronto_pago_dias:e.target.value })}/></Field><Field label="Pronto pago · %"><input type="number" min="0" max="100" step="0.01" value={nf.pronto_pago_porcentaje} onChange={e => setNf({ ...nf,pronto_pago_porcentaje:e.target.value })}/></Field><Field label="Contacto"><input value={nf.contacto} onChange={e => setNf({ ...nf,contacto:e.target.value })}/></Field><Field label="Teléfono"><input value={nf.telefono} onChange={e => setNf({ ...nf,telefono:e.target.value })}/></Field><div className="modal-actions"><button className="ghost" onClick={() => setOpen(false)}>Cancelar</button><button onClick={async()=>{if(!nf.nombre.trim())return alert('Nombre requerido');try{await api.createProv({ ...nf,nombre:nf.nombre.trim(),contacto:nf.contacto||null,telefono:nf.telefono||null,alias:nf.alias||null,dias_entrega:nf.dias_entrega||null,pronto_pago_dias:nf.pronto_pago_dias===''?null:+nf.pronto_pago_dias,pronto_pago_porcentaje:nf.pronto_pago_porcentaje===''?null:+nf.pronto_pago_porcentaje});setNf({nombre:'',contacto:'',telefono:'',alias:'',dias_entrega:'',pronto_pago_dias:'',pronto_pago_porcentaje:''});setOpen(false);recargar();}catch(e){alert(e.message)}}}>Guardar</button></div></Modal>
  </section>;
}

export default Proveedores;
